/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labextrap2_diegoordonez;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author 50432
 */
public class Administrador extends javax.swing.JFrame {
static ArrayList<Equipo> equipos = new ArrayList();
static ArrayList<Deporte> sports = new ArrayList();
    public Administrador() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jpm_listar = new javax.swing.JMenuItem();
        jpm_mostrar = new javax.swing.JMenuItem();
        jdia_Listar_equip = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlist_equi = new javax.swing.JList<>();
        jdia_most_tabla = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jp_tree = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_principal = new javax.swing.JTree();
        jp_equipo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_equip_nom = new javax.swing.JTextField();
        jt_equip_ptn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jp_torneo = new javax.swing.JPanel();
        jcom_torn_equi = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jt_torn_prin = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jp_deporte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jt_sport_nom = new javax.swing.JTextField();
        jbt_agre = new javax.swing.JButton();

        jpm_listar.setText("jMenuItem1");
        jpm_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpm_listarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jpm_listar);

        jpm_mostrar.setText("jMenuItem2");
        jPopupMenu1.add(jpm_mostrar);

        jlist_equi.setModel(new DefaultListModel()
        );
        jScrollPane2.setViewportView(jlist_equi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(583, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jdia_Listar_equipLayout = new javax.swing.GroupLayout(jdia_Listar_equip.getContentPane());
        jdia_Listar_equip.getContentPane().setLayout(jdia_Listar_equipLayout);
        jdia_Listar_equipLayout.setHorizontalGroup(
            jdia_Listar_equipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdia_Listar_equipLayout.setVerticalGroup(
            jdia_Listar_equipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jdia_most_tablaLayout = new javax.swing.GroupLayout(jdia_most_tabla.getContentPane());
        jdia_most_tabla.getContentPane().setLayout(jdia_most_tablaLayout);
        jdia_most_tablaLayout.setHorizontalGroup(
            jdia_most_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdia_most_tablaLayout.setVerticalGroup(
            jdia_most_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q3");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q4");
        treeNode1.add(treeNode2);
        jt_principal.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_principalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_principal);

        javax.swing.GroupLayout jp_treeLayout = new javax.swing.GroupLayout(jp_tree);
        jp_tree.setLayout(jp_treeLayout);
        jp_treeLayout.setHorizontalGroup(
            jp_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_treeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(555, Short.MAX_VALUE))
        );
        jp_treeLayout.setVerticalGroup(
            jp_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_treeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tree", jp_tree);

        jLabel2.setText("Deporte");

        jLabel3.setText("Nombre");

        jLabel4.setText("Puntos");

        jt_equip_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_equip_nomActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar equipo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_equipoLayout = new javax.swing.GroupLayout(jp_equipo);
        jp_equipo.setLayout(jp_equipoLayout);
        jp_equipoLayout.setHorizontalGroup(
            jp_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_equipoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jp_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jp_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_equip_nom)
                    .addComponent(jt_equip_ptn, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_equipoLayout.createSequentialGroup()
                .addContainerGap(393, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(331, 331, 331))
        );
        jp_equipoLayout.setVerticalGroup(
            jp_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_equipoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_equip_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_equip_ptn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar equipo", jp_equipo);

        jcom_torn_equi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel5.setText("Deporte");

        jLabel6.setText("nombre");

        jButton2.setText("Agregar t");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_torneoLayout = new javax.swing.GroupLayout(jp_torneo);
        jp_torneo.setLayout(jp_torneoLayout);
        jp_torneoLayout.setHorizontalGroup(
            jp_torneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_torneoLayout.createSequentialGroup()
                .addGroup(jp_torneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_torneoLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jp_torneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_torneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcom_torn_equi, 0, 146, Short.MAX_VALUE)
                            .addComponent(jt_torn_prin)))
                    .addGroup(jp_torneoLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        jp_torneoLayout.setVerticalGroup(
            jp_torneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_torneoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jp_torneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcom_torn_equi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jp_torneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_torn_prin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Torneo", jp_torneo);

        jLabel1.setText("Nombre");

        jt_sport_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_sport_nomActionPerformed(evt);
            }
        });

        jbt_agre.setText("Agregar");
        jbt_agre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_agreMouseClicked(evt);
            }
        });
        jbt_agre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_agreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_deporteLayout = new javax.swing.GroupLayout(jp_deporte);
        jp_deporte.setLayout(jp_deporteLayout);
        jp_deporteLayout.setHorizontalGroup(
            jp_deporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_deporteLayout.createSequentialGroup()
                .addGroup(jp_deporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_deporteLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_sport_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_deporteLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jbt_agre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        jp_deporteLayout.setVerticalGroup(
            jp_deporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_deporteLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jp_deporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_sport_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jbt_agre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Deporte", jp_deporte);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_sport_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_sport_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_sport_nomActionPerformed

    private void jt_equip_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_equip_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_equip_nomActionPerformed

    private void jbt_agreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_agreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_agreActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      Equipo equip = new Equipo(jt_equip_nom.getText(), Integer.parseInt(jt_equip_ptn.getText()));
      equipos.add(equip);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jbt_agreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_agreMouseClicked
      Deporte sport = new Deporte(jt_sport_nom.getText());
      sports.add(sport);
      
      DefaultTreeModel m = (DefaultTreeModel) jt_principal.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode q1 = (DefaultMutableTreeNode) raiz.getChildAt(0);
        DefaultMutableTreeNode q2 = (DefaultMutableTreeNode) raiz.getChildAt(1);
        DefaultMutableTreeNode q3 = (DefaultMutableTreeNode) raiz.getChildAt(2);
        DefaultMutableTreeNode q4 = (DefaultMutableTreeNode) raiz.getChildAt(3);
        Torneo t = new Torneo(jt_torn_prin.getText(), jcom_torn_equi.getSelectedItem().toString());
        for (int i = 0; i < q1.getChildCount(); i++) {
            if (q1.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q1.getChildAt(i)).add(p);
            }
        }
        for (int i = 0; i < q2.getChildCount(); i++) {
            if (q2.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q2.getChildAt(i)).add(p);
            }
        }
        for (int i = 0; i < q3.getChildCount(); i++) {
            if (q3.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q3.getChildAt(i)).add(p);
            }
        }
        for (int i = 0; i < q4.getChildCount(); i++) {
            if (q4.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q4.getChildAt(i)).add(p);
            }
        }

        m.reload();
    }//GEN-LAST:event_jbt_agreMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        DefaultTreeModel m = (DefaultTreeModel) jt_principal.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode q1 = (DefaultMutableTreeNode) raiz.getChildAt(0);
        DefaultMutableTreeNode q2 = (DefaultMutableTreeNode) raiz.getChildAt(1);
        DefaultMutableTreeNode q3 = (DefaultMutableTreeNode) raiz.getChildAt(2);
        DefaultMutableTreeNode q4 = (DefaultMutableTreeNode) raiz.getChildAt(3);
        Torneo t = new Torneo(jt_torn_prin.getText(), jcom_torn_equi.getSelectedItem().toString());
        for (int i = 0; i < q1.getChildCount(); i++) {
            if (q1.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q1.getChildAt(i)).add(p);
            }
        }
        for (int i = 0; i < q2.getChildCount(); i++) {
            if (q2.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q2.getChildAt(i)).add(p);
            }
        }
        for (int i = 0; i < q3.getChildCount(); i++) {
            if (q3.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q3.getChildAt(i)).add(p);
            }
        }
        for (int i = 0; i < q4.getChildCount(); i++) {
            if (q4.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q4.getChildAt(i)).add(p);
            }
        }

        m.reload();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jt_principalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_principalMouseClicked
        if (evt.isMetaDown()) {
            
           int sec = jt_principal.getRowForLocation(evt.getX(), evt.getY());
            if (sec >= 0) {
                jPopupMenu1.show(jt_principal, evt.getX(), evt.getY());
                
                
            }
            
        }
    }//GEN-LAST:event_jt_principalMouseClicked

    private void jpm_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpm_listarActionPerformed
      
        jdia_Listar_equip.pack();
        jdia_Listar_equip.setModal(false);
        listarList();
    }//GEN-LAST:event_jpm_listarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void listarList(){
    
        DefaultListModel modlist = (DefaultListModel)jlist_equi.getModel();
        modlist.removeAllElements();
        for (Equipo equipo : equipos) {
            modlist.addElement(equipo);
            
            
        }jlist_equi.setModel(modlist);
        
    }
    public void llenarcom(){
        DefaultComboBoxModel modelcom = (DefaultComboBoxModel)jcom_torn_equi.getModel();
        modelcom.removeAllElements();
        for (Deporte sport : sports) {
            modelcom.addElement(sport);
            
        }jcom_torn_equi.setModel(modelcom);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbt_agre;
    private javax.swing.JComboBox<String> jcom_torn_equi;
    private javax.swing.JDialog jdia_Listar_equip;
    private javax.swing.JDialog jdia_most_tabla;
    private javax.swing.JList<String> jlist_equi;
    private javax.swing.JPanel jp_deporte;
    private javax.swing.JPanel jp_equipo;
    private javax.swing.JPanel jp_torneo;
    private javax.swing.JPanel jp_tree;
    private javax.swing.JMenuItem jpm_listar;
    private javax.swing.JMenuItem jpm_mostrar;
    private javax.swing.JTextField jt_equip_nom;
    private javax.swing.JTextField jt_equip_ptn;
    private javax.swing.JTree jt_principal;
    private javax.swing.JTextField jt_sport_nom;
    private javax.swing.JTextField jt_torn_prin;
    // End of variables declaration//GEN-END:variables
}
